//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChinessResturantAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMenue
    {
        public string OrdeRreference { get; set; }
        public string ItenNo { get; set; }
        public string qty { get; set; }
    
        public virtual Menue Menue { get; set; }
        public virtual Order Order { get; set; }
    }
}
